GiTD/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about' => 'pages#about'
  get '/rules' => 'pages#rules'
  resources :games do
    member do
      put "like", to: "games#vote", vote: :upvote
      put "dislike", to: "games#vote" , vote: :downvote
      put "unvote", to: "games#vote", vote: :unvote
    end
  end
  resources :jams
  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forum'

  mount Commontator::Engine => '/commontator'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: "registrations"}

  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end
end

GiTD/app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  belongs_to :jam
  mount_uploaders :screenshots, ScreenshotUploader
  mount_uploader :game_file, GameFileUploader
  mount_uploaders :multifiles, GameFileUploader

  validates_presence_of :title
  validates_uniqueness_of :title, :case_sensitive => false
  validates_presence_of :jam_id

  acts_as_commontable
  acts_as_votable
end

GiTD/app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :set_game, only: [:show, :edit, :update, :destroy, :vote]
  before_action :authenticate_user!, except: [:index, :show]
  authorize_resource
  skip_authorize_resource :only => [:new, :create]

  # GET /games
  # GET /games.json
  def index
    @games = Game.order(jam_id: :asc)
    @jams = Jam.order(title: :desc)
  end

  # GET /games/1
  # GET /games/1.json
  def show
    commontator_thread_show(@game)
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.games.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_path(@game.title), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: game_path(@game.title) }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_path(@game.title), notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: game_path(@game.title) }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    case params[:vote]
    when :upvote
      @game.upvote_by current_user
    when :downvote
      @game.downvote_by current_user
    when :unvote
      @game.unvote_by current_user
    end
    redirect_to games_path      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find_by(title: params[:title]) || Game.find_by(title: params[:id]) || Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :description, :external_link, :game_file, :url, :height, :width, :jam_id, {screenshots:  []}, {multifiles: []})
    end
end

GiTD/app/helpers/games_helper.rb
module GamesHelper
end

GiTD/app/views/games/_form.html.erb
<%= simple_form_for(@game, html: {multipart: true}) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :title, autofocus: true, required: true, label: false, placeholder: "Title", input_html: {class: "form-conrol"} %>
    <%= f.input :description, label: false, placeholder: "Description", input_html: {class: "form-conrol"} %>
    <%= f.input :external_link, label: false, placeholder: "Link to game on external site, if applicable", input_html: {class: "form-conrol"} %>
    <%= f.input :url, label: false, placeholder: "Iframe link, if applicable", input_html: {class: "form-conrol"} %>
    <%= f.input :width, label: false, placeholder: "Width", input_html: {class: "form-conrol"} %>
    <%= f.input :height, label: false, placeholder: "Height", input_html: {class: "form-conrol"} %>
    <%= f.input :game_file, as: :file, label: "Upload a single game file: (.swf or .unity3d)" %>
    <%= f.input :multifiles, as: :file, label: "Upload multiple game files: (still working on folders)", input_html: { multiple: true} %>
    <%= f.input :screenshots, as: :file, label: "Upload screenshots:", input_html: {multiple: true} %>
    <%= f.association :jam, required: true, label: false, prompt: "Which Jam was this for?", input_html: {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: "btn btn-custom btn-block" %>
  </div>
<% end %>

GiTD/app/views/games/_game.html.erb
<div class="col-md-3">
  <%= link_to game_path(game.title) do %>
    <div class="thumbnail tn-custom">
      <%= get_screenies game %>
    </div>
    <div class="caption">
      <h3><%= game.title %></h3>
      <h5>By <%= game.user.username %></h5>
      <% if current_user && !(current_user.voted_for? game) %>
        <%= link_to like_game_path(game.title), method: :put do %>
          <button class="btn btn-success">
            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
          </button>
          <% end %>
          <%= link_to dislike_game_path(game.title), method: :put do %>
          <button class="btn btn-warning">
            <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
          </button>
        <% end %>
      <% else %>
        Score: <%= game.get_upvotes.size %> 
        <% if current_user %>
          <%= link_to unvote_game_path(game.title), method: :put do %>
            <button class="btn btn-info">
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel vote
            </button>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

GiTD/app/views/games/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h1>Editing Game</h1>

      <%= render 'form' %>

      <%= link_to game_path(@game.title) do %> 
        <button class="btn btn-custom">Show</button>
      <% end %>
      <%= link_to games_path do %>
        <button class="btn btn-custom">Back</button>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

GiTD/app/views/games/index.html.erb
<div class="container">
<h1>
  All Games
  <% if current_user %>
    <%= link_to new_game_path do %>
      <button class="btn btn-primary">New Game</button>
    <% end %>
  <% end %>
</h1>
  <% @jams.each do |jam| %>
    <div class="row">
      <%= link_to jam_path(jam.id) do %>
        <h2><button class="btn btn-lg btn-custom">GiTD #<%= jam.title %></button></h2>
      <% end %>
      <div class="row">
        <% @games.each do |game| %>
          <% if game.jam == jam %>
            <%= render game %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

GiTD/app/views/games/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h1>New Game</h1>

      <%= render 'form' %>

      <%= link_to games_path do %>
        <button class="btn btn-custom">Back</button>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

GiTD/app/views/games/show.html.erb
<div class="jumbotron jt-custom">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
      <h1><%= @game.title %></h1>
      </div>
      <div class="col-md-6">
        <h3>
          By <%= @game.user.username %>
          <% if current_user == @game.user || current_user.try(:admin?) || current_user.try(:moderator?) %>
            <%= link_to edit_game_path(@game.title) do %>
              <button class="btn btn-warning">Edit</button>
            <% end %>
          <% end %>
          <%= link_to games_path do %>
            <button class="btn btn-info">Back</button>
          <% end %>
          <% if current_user.try(:admin?) %>
            <%= link_to @game.title, method: :delete, data: {confirm: "Are you sure?"} do %>
              <button class="btn btn-danger">Delete</button>
            <% end %>
          <% end %>
        </h3>
        <h5><%= format_text @game.description %></h5>
      </div>
    </div>
    <div class="row">
      <% if !@game.external_link.blank? %>
        <% if @game.external_link=~/^.*kongregate.*$/ %>
          <h2><%= link_to "Play on Kongregate", (get_site @game.external_link), target: "_blank" %></h2>
        <% elsif @game.external_link=~/^.*fastswf.*$/ %>
          <h2><%= link_to "Play on Fastswf.com", (get_site @game.external_link), target: "_blank" %></h2>
        <% else %>
          <h2><%= link_to "Play externally", (get_site @game.external_link), target: "_blank" %></h2>
        <% end %>
      <% end %>
    </div>
    <div class="row">
      <% if !@game.game_file.blank? %>
        <embed src="<%= @game.game_file_url %>" width="<%= @game.width %>" height="<%= @game.height %>" />
      <% elsif !@game.url.blank? %>
        <iframe width="<%= @game.width %>" height="<%= @game.height %>" src="<%= get_site @game.url %>" frameborder="0" allowfullscreen></iframe>
      <% elsif !@game.multifiles.blank? %>
      <%= @game.multifiles %>
        <iframe width="<%= @game.width %>" height="<%= @game.height %>" src="<%= @game.multifiles[0].url %>" frameborder="0" allowfullscreen></iframe>
        <%#= render :file => @game.multifiles_url %>
      <% end %>
    </div>
    <div class="row">
      <%= commontator_thread(@game) %>
    </div>
  </div>
</div>